[pytest]
asyncio_mode = auto
filterwarnings =
    ignore:Please use `import python_multipart` instead\.
    ignore:Using extra keyword arguments on `Field` is deprecated.*coerce_numbers_to_str.*
    ignore:urllib3 v2 only supports OpenSSL 1\.1\.1\+, currently the 'ssl' module is compiled with 'LibreSSL 2\.8\.3'.*
