import { Message, Agent } from '../types';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import StockChartCard from './StockChartCard';
import ReasoningDisplay from './ReasoningDisplay';
import FollowUpQuestions from './FollowUpQuestions';
import { financialTableComponents } from './FinancialTable';
import { AgentChart } from './AgentChart';
import { useState, useEffect, useRef } from 'react';
import { Sparkles } from 'lucide-react';

const AGENT_DISPLAY_NAMES: Record<string, string> = {
  auto: 'Auto',
  research: 'Finance Q&A',
  analyst: 'Equity Analyst',
  market: 'Market Analyst',
  dcf: 'DCF Analyst',
  portfolio: 'Portfolio Analyzer',
  earnings: 'Earnings Analyst',
};

interface MessageProps {
  message: Message;
  agent: Agent;
  isStreaming?: boolean;
  onFollowUpClick?: (question: string) => void;
}

function preprocessChartPlaceholders(content: string): string {
  return content.replace(
    /\{\{CHART:([^}]+)\}\}/g,
    (_, id) => `\`\`\`chart:${id.trim()}\n\`\`\``
  );
}

function MessageComponent({ message, agent, isStreaming = false, onFollowUpClick }: MessageProps) {
  const isUser = message.role === 'user';
  const isSystem = message.role === 'system';
  const [isReasoningCollapsed, setIsReasoningCollapsed] = useState(false);
  const wasStreamingRef = useRef(isStreaming);

  // Auto-collapse reasoning when streaming finishes
  useEffect(() => {
    if (wasStreamingRef.current && !isStreaming) {
      setIsReasoningCollapsed(true);
    }
    wasStreamingRef.current = isStreaming;
  }, [isStreaming]);

  if (!message.content && !message.thinkingSteps?.length) return null;

  // Filter out ReAct format markers, ASCII borders, and tool output headers
  const cleanContent = (content: string): string => {
    if (!content) return '';
    return content
      // ReAct chain-of-thought markers
      .replace(/<thinking>[\s\S]*?<\/thinking>/g, '')
      .replace(/<reflection>[\s\S]*?<\/reflection>/g, '')
      .replace(/\*\*PLAN:\*\*[\s\S]*?(?=\n\n|\*\*|$)/g, '')
      .replace(/Plan:[\s\S]*?(?=\n\n|Thought:|$)/g, '')
      .replace(/Thought:[\s\S]*?(?=\n\nAction:|$)/g, '')
      .replace(/Reflection:[\s\S]*?(?=\n\n|$)/g, '')
      .replace(/Action:[\s\S]*?(?=\n\nAction Input:|$)/g, '')
      .replace(/Action Input:[\s\S]*?(?=\n\nObservation:|$)/g, '')
      .replace(/Observation:[\s\S]*?(?=\n\nThought:|$)/g, '')
      .replace(/Final Answer:\s*/g, '')
      // ASCII border lines (4+ repeated =, -, or * on a line by themselves)
      .replace(/^[=\-\*]{4,}\s*$/gm, '')
      // ASCII border lines with content (e.g., "=== Title ===", "--- Section ---")
      .replace(/^={3,}[^|]{0,80}={3,}\s*$/gm, '')
      .replace(/^-{3,}[^|]{0,80}-{3,}\s*$/gm, '')
      // Tool output headers that may bleed into the final response
      .replace(/^(Industry Analysis|Competitor Analysis|Competitive Moat Analysis|Management Quality Analysis|Financial Metrics|Web Search Results|Stock Information) for [^\n]+\n/gm, '')
      // DCF tool artifacts
      .replace(/^Generated by Finance DCF Agent[^\n]*$/gm, '')
      .replace(/^DISCLAIMER[\s\S]*?(?=\n##|\n#|$)/gm, '')
      // Strip chart system artifacts if LLM accidentally echoes them
      .replace(/\[CHART_INSTRUCTION:[^\]]*\]/g, '')
      .replace(/---CHART_DATA:[^-\n]*---[\s\S]*?---END_CHART_DATA:[^-\n]*---/g, '')
      // Collapse triple+ blank lines down to double
      .replace(/\n{3,}/g, '\n\n')
      .trim();
  };

  const displayContent = isUser ? message.content : cleanContent(message.content);
  const processedContent = isUser ? displayContent : preprocessChartPlaceholders(displayContent);

  // Detect tickers from backend metadata only (extracted from user query).
  // Do NOT extract tickers from assistant response content — it causes false
  // positives (e.g., market analysis mentioning sector ETFs like XLE, XLK).
  // For the market agent, default to SPY vs QQQ when no specific ticker was asked.
  const tickers: string[] = (() => {
    if (isUser || isSystem) return [];
    if (message.ticker) return [message.ticker];
    if (message.agentType === 'market') return ['SPY', 'QQQ'];
    return [];
  })();

  const handleCopyReasoning = () => {
    if (!message.thinkingSteps) return;
    let text = '=== AGENT REASONING ===\n\n';
    message.thinkingSteps.forEach((step, i) => {
      text += `${i + 1}. [${step.type}] ${step.content || step.tool || ''}\n`;
    });
    navigator.clipboard.writeText(text);
  };

  // System messages
  if (isSystem) {
    return (
      <div className="flex justify-center my-4 animate-fade-in">
        <div
          className="px-4 py-1.5 rounded-full text-xs"
          style={{
            fontFamily: 'Inter, sans-serif',
            color: '#9CA3AF',
            background: 'rgba(0, 0, 0, 0.03)',
          }}
        >
          <ReactMarkdown className="inline">{message.content}</ReactMarkdown>
        </div>
      </div>
    );
  }

  // User message - dark pill bubble
  if (isUser) {
    return (
      <div className="flex justify-end animate-fade-in">
        <div className="user-message">
          {displayContent}
        </div>
      </div>
    );
  }

  // Assistant message - document-style flow
  return (
    <div className="animate-fade-in">
      {/* Reasoning Display */}
      {message.thinkingSteps && message.thinkingSteps.length > 0 && (
        <div className="mb-3">
          <ReasoningDisplay
            steps={message.thinkingSteps}
            isStreaming={isStreaming}
            isCollapsed={isReasoningCollapsed}
            onToggleCollapse={() => setIsReasoningCollapsed(!isReasoningCollapsed)}
            onCopy={handleCopyReasoning}
          />
        </div>
      )}

      {/* Stock Chart */}
      {tickers.length > 0 && (
        <div className="mb-4">
          <StockChartCard tickers={tickers} />
        </div>
      )}

      {/* Response content */}
      {displayContent && (
        <div className="assistant-response">
          <div className="mb-2" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span
              className="text-xs font-medium"
              style={{ fontFamily: 'Inter, sans-serif', color: '#9CA3AF' }}
            >
              {message.isAutoRouted
                ? (message.agentType
                    ? AGENT_DISPLAY_NAMES[message.agentType] || message.agentType
                    : 'Routing...')
                : agent.name}
            </span>
            {message.isAutoRouted && (
              <span className="routing-badge">
                <Sparkles style={{ width: 9, height: 9, color: '#10B981' }} />
                Auto
              </span>
            )}
          </div>
          <div className="prose-gray">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={{
                ...financialTableComponents,
                code: ({ node, inline, className, children, ...props }: any) => {
                  const match = /^chart:(.+)$/.exec((className ?? '').replace('language-', ''));
                  if (match && !inline) {
                    const chartId = match[1];
                    const chartData = message.chartsById?.[chartId];
                    if (chartData) return <AgentChart {...chartData} />;
                    return null;
                  }
                  return <code className={className} {...props}>{children}</code>;
                }
              }}
            >{processedContent}</ReactMarkdown>
          </div>
          {!isStreaming && message.followUps && message.followUps.length > 0 && onFollowUpClick && (
            <FollowUpQuestions
              questions={message.followUps}
              onQuestionClick={onFollowUpClick}
            />
          )}
        </div>
      )}
    </div>
  );
}

export default MessageComponent;
