"""initial_schema

Revision ID: 33deaf934141
Revises: 
Create Date: 2026-06-03 19:33:56.297906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33deaf934141'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.alter_column('share_slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=12),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_analyses_share_slug'), ['share_slug'], unique=True)

    with op.batch_alter_table('hire_proposals', schema=None) as batch_op:
        batch_op.alter_column('source_task_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'research_tasks', ['source_task_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('research_task_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_task_documents_updated_at'))

    with op.batch_alter_table('research_tasks', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('owner_agent_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('assigned_agent_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('source_heartbeat_run_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'heartbeat_runs', ['source_heartbeat_run_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'scheduled_agents', ['assigned_agent_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'scheduled_agents', ['owner_agent_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('scheduled_agents', schema=None) as batch_op:
        batch_op.alter_column('role_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('role_title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('role_family',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('manager_agent_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'scheduled_agents', ['manager_agent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_agents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('manager_agent_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('role_family',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('role_title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('role_key',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('research_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('source_heartbeat_run_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('assigned_agent_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('owner_agent_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('project_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('research_task_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_task_documents_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('hire_proposals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('source_task_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_share_slug'))
        batch_op.alter_column('share_slug',
               existing_type=sa.String(length=12),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
