"""
Custom callback handler for streaming agent responses via SSE.

This module provides the StreamingCallbackHandler class that captures
agent thinking, tool calls, and results for real-time streaming to clients.
"""

import asyncio
import os
import sys
from typing import Any, Dict, List, Optional

from langchain.callbacks.base import AsyncCallbackHandler
from langchain.schema import AgentAction, AgentFinish, LLMResult

# Add parent directory to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from shared.constants import TOOL_DESCRIPTIONS, TOOL_TO_PHASE
from backend.config import (
    MIN_THOUGHT_LENGTH, MIN_PLAN_STEPS, MIN_STEP_LENGTH,
    MAX_PARAM_DISPLAY_LENGTH
)
from backend.utils.llm_parser import LLMOutputParser


class StreamingCallbackHandler(AsyncCallbackHandler):
    """
    Custom callback handler to stream agent thinking process with XML tag extraction.

    This handler captures:
    - LLM thinking/reasoning in <thinking> tags
    - LLM reflections in <reflection> tags
    - Tool calls with friendly descriptions
    - Tool results and source extraction
    - Phase transitions during agent execution

    Events are streamed to an asyncio Queue for SSE delivery to clients.
    """

    @staticmethod
    def _ensure_str(value) -> str:
        """Convert Anthropic content blocks (list) or other types to a plain string."""
        if isinstance(value, str):
            return value
        if isinstance(value, list):
            parts = []
            for block in value:
                if isinstance(block, dict):
                    parts.append(block.get("text", ""))
                elif isinstance(block, str):
                    parts.append(block)
                else:
                    text = getattr(block, "text", None)
                    if text:
                        parts.append(str(text))
            return "".join(parts)
        return str(value) if value is not None else ""

    def __init__(self, queue: asyncio.Queue):
        """
        Initialize the streaming callback handler.

        Args:
            queue: Async queue for streaming events to SSE response
        """
        self.queue = queue
        self.tool_count = 0
        self.current_phase = None  # Track current reasoning phase
        # State for XML tag streaming
        self._token_buffer = ""
        self._in_thinking = False
        self._in_reflection = False
        self._in_final_answer = False
        self._plan_emitted = False
        self._thinking_buffer = ""
        self._reflection_buffer = ""

    async def on_llm_start(self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any) -> None:
        """Called when LLM starts"""
        if self.tool_count == 0:  # Only show for first LLM call
            await self.queue.put({"type": "thinking_start", "phase": "analyzing"})
        # Reset token buffer for this LLM call
        self._token_buffer = ""
        self._in_thinking = False
        self._in_reflection = False
        self._thinking_buffer = ""
        self._reflection_buffer = ""

    async def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        """Called for each token generated by LLM (streaming mode) - extracts XML thinking/reflection tags"""
        token = self._ensure_str(token)
        self._token_buffer += token

        # === Handle <thinking> tags ===
        # Detect start of thinking block
        if '<thinking>' in self._token_buffer and not self._in_thinking and not self._in_reflection:
            self._in_thinking = True
            await self.queue.put({"type": "thinking_start", "phase": "reasoning"})
            # Extract any content after <thinking> tag
            after_tag = self._token_buffer.split('<thinking>')[-1]
            if after_tag and '</thinking>' not in after_tag:
                self._thinking_buffer = after_tag
                await self.queue.put({"type": "thinking_chunk", "content": after_tag})
            # Clear buffer up to the tag to avoid re-detection
            self._token_buffer = after_tag

        # Stream thinking content
        elif self._in_thinking and '</thinking>' not in self._token_buffer:
            self._thinking_buffer += token
            await self.queue.put({"type": "thinking_chunk", "content": token})

        # Detect end of thinking block
        elif self._in_thinking and '</thinking>' in self._token_buffer:
            self._in_thinking = False
            # Extract content before closing tag
            before_close = self._token_buffer.split('</thinking>')[0]
            if before_close and before_close not in self._thinking_buffer:
                await self.queue.put({"type": "thinking_chunk", "content": before_close})
            await self.queue.put({"type": "thinking_end"})
            # Keep content after closing tag
            self._token_buffer = self._token_buffer.split('</thinking>')[-1]
            self._thinking_buffer = ""

        # === Handle <reflection> tags ===
        # Detect start of reflection block
        elif '<reflection>' in self._token_buffer and not self._in_reflection and not self._in_thinking:
            self._in_reflection = True
            await self.queue.put({"type": "reflection_start"})
            # Extract any content after <reflection> tag
            after_tag = self._token_buffer.split('<reflection>')[-1]
            if after_tag and '</reflection>' not in after_tag:
                self._reflection_buffer = after_tag
                await self.queue.put({"type": "reflection_chunk", "content": after_tag})
            self._token_buffer = after_tag

        # Stream reflection content
        elif self._in_reflection and '</reflection>' not in self._token_buffer:
            self._reflection_buffer += token
            await self.queue.put({"type": "reflection_chunk", "content": token})

        # Detect end of reflection block
        elif self._in_reflection and '</reflection>' in self._token_buffer:
            self._in_reflection = False
            # Extract content before closing tag
            before_close = self._token_buffer.split('</reflection>')[0]
            if before_close and before_close not in self._reflection_buffer:
                await self.queue.put({"type": "reflection_chunk", "content": before_close})
            await self.queue.put({"type": "reflection_end", "content": self._reflection_buffer})
            self._token_buffer = self._token_buffer.split('</reflection>')[-1]
            self._reflection_buffer = ""

    async def on_llm_end(self, response: LLMResult, **kwargs: Any) -> None:
        """Called when LLM ends - extract reasoning from output"""
        try:
            # Get the LLM's generated text
            if response.generations and len(response.generations) > 0:
                generation = response.generations[0]
                if generation and len(generation) > 0:
                    # Anthropic may return content as list of blocks; ensure string
                    raw_text = generation[0].text
                    if not isinstance(raw_text, str):
                        msg = getattr(generation[0], 'message', None)
                        raw_text = self._ensure_str(
                            getattr(msg, 'content', raw_text) if msg else raw_text
                        )
                    llm_output = raw_text

                    # Extract thinking from XML tags (fallback if streaming missed it)
                    thinking = self._extract_xml_thinking(llm_output)
                    if thinking and not self._thinking_buffer:
                        await self.queue.put({
                            "type": "agent_thought",
                            "content": thinking
                        })

                    # Fallback: extract ReAct Thought: content (for OpenAI models)
                    if not thinking and not self._thinking_buffer:
                        react_thought = self._extract_thought(llm_output)
                        if react_thought:
                            await self.queue.put({
                                "type": "agent_thought",
                                "content": react_thought
                            })

                    # Extract plan ONLY from actual thinking content (not full LLM output)
                    # This prevents the final answer from being mistaken for a plan
                    if thinking and not self._plan_emitted:
                        plan = self._extract_plan_from_thinking(thinking)
                        if plan:
                            await self.queue.put({
                                "type": "plan_created",
                                "plan": plan
                            })
                            self._plan_emitted = True

                    # Extract reflection from XML tags (fallback)
                    reflection = self._extract_xml_reflection(llm_output)
                    if reflection and not self._reflection_buffer:
                        await self.queue.put({
                            "type": "reflection",
                            "content": reflection
                        })

                    # Fallback: extract ReAct Reflection: content
                    if not reflection and not self._reflection_buffer:
                        react_reflection = self._extract_reflection(llm_output)
                        if react_reflection:
                            await self.queue.put({
                                "type": "reflection",
                                "content": react_reflection
                            })

        except Exception as e:
            # Log but don't fail - thoughts are nice-to-have
            import logging
            logging.debug(f"Could not extract thought/plan/reflection: {e}")

    async def on_agent_action(self, action: AgentAction, **kwargs: Any) -> None:
        """Called when agent takes an action"""
        self.tool_count += 1
        tool_name = action.tool
        tool_input = action.tool_input

        # Detect phase transition
        new_phase = TOOL_TO_PHASE.get(tool_name)
        if new_phase and new_phase != self.current_phase:
            self.current_phase = new_phase
            await self.queue.put({
                "type": "phase_start",
                "phase": new_phase,
                "content": self._get_phase_description(new_phase)
            })

        # Extract search queries for search_web tool
        if tool_name == 'search_web':
            query = self._extract_search_query(tool_input)
            if query:
                await self.queue.put({
                    "type": "search_query",
                    "query": query
                })

        # Get friendly description
        friendly_desc = TOOL_DESCRIPTIONS.get(tool_name, f'🔍 Using {tool_name}')

        # Send as a thought (user-friendly description)
        await self.queue.put({
            "type": "thought",
            "content": friendly_desc
        })

        # Send the tool info (for technical details if needed)
        # Only include simple, readable input parameters
        if isinstance(tool_input, dict):
            # Filter out complex/code-like inputs
            simple_params = {}
            for k, v in tool_input.items():
                # Only show simple parameters, skip complex ones
                if isinstance(v, (str, int, float, bool)) and len(str(v)) < MAX_PARAM_DISPLAY_LENGTH:
                    simple_params[k] = v

            if simple_params:
                input_str = ", ".join([f"{k}={v}" for k, v in simple_params.items()])
            else:
                input_str = None
        else:
            input_str = str(tool_input)[:MAX_PARAM_DISPLAY_LENGTH] if tool_input else None

        await self.queue.put({
            "type": "tool",
            "tool": friendly_desc,  # Use friendly name
            "input": input_str
        })

    async def on_tool_end(self, output: str, **kwargs: Any) -> None:
        """Called when tool execution ends"""
        output = self._ensure_str(output)
        # Extract sources from output
        sources = self._extract_sources_from_output(output)
        for source in sources:
            await self.queue.put({
                "type": "source_review",
                "source": source
            })

        # Send completion indicator
        await self.queue.put({
            "type": "tool_result",
            "content": "✓ Data retrieved"
        })

    async def on_agent_finish(self, finish: AgentFinish, **kwargs: Any) -> None:
        """Called when agent finishes"""
        await self.queue.put({"type": "agent_finish"})

    def _get_phase_description(self, phase: str) -> str:
        """Get friendly description for reasoning phase"""
        descriptions = {
            'gathering_data': 'Gathering financial data',
            'searching': 'Searching for market information',
            'reviewing': 'Reviewing sources and news',
            'analyzing': 'Analyzing data and trends',
            'calculating': 'Performing calculations',
            'synthesizing': 'Synthesizing findings'
        }
        return descriptions.get(phase, 'Processing')

    def _extract_search_query(self, tool_input) -> str:
        """Extract search query from tool input"""
        if isinstance(tool_input, dict):
            return tool_input.get('query', '')
        return str(tool_input) if tool_input else ''

    def _extract_sources_from_output(self, output: str) -> List[Dict[str, str]]:
        """Extract source metadata from tool output"""
        sources = []
        output_lower = output.lower()

        # Check for Financial Datasets API usage
        if 'financial' in output_lower and any(term in output_lower for term in ['datasets', 'data', 'metrics']):
            sources.append({
                "title": "Financial Datasets AI",
                "domain": "financialdatasets.ai",
                "type": "financial_data"
            })

        # Check for Perplexity/web search results
        if any(term in output_lower for term in ['perplexity', 'web search', 'sources:', 'according to']):
            sources.append({
                "title": "Web Search Results",
                "domain": "perplexity.ai",
                "type": "web_search"
            })

        # Check for news sources
        if any(term in output_lower for term in ['news', 'article', 'report', 'announcement']):
            if not any(s['type'] == 'web_search' for s in sources):  # Avoid duplicates
                sources.append({
                    "title": "News Sources",
                    "domain": "news aggregator",
                    "type": "news"
                })

        # Check for calculations
        if any(term in output_lower for term in ['calculated', 'computation', 'dcf', 'valuation', 'intrinsic value']):
            if not any(s['type'] == 'financial_data' for s in sources):  # Avoid duplicates
                sources.append({
                    "title": "Internal Calculation",
                    "domain": "valuation model",
                    "type": "calculation"
                })

        return sources

    def _extract_thought(self, llm_output: str) -> str:
        """Extract the Thought portion from ReAct agent output"""
        if not llm_output:
            return ""

        lines = llm_output.strip().split('\n')
        thought_lines = []
        in_thought = False

        for line in lines:
            line_stripped = line.strip()

            # Start of thought section
            if line_stripped.lower().startswith('thought:'):
                in_thought = True
                # Extract everything after "Thought:"
                thought_text = line_stripped[8:].strip()
                if thought_text:
                    thought_lines.append(thought_text)

            # End of thought section when we hit Action or Final Answer
            elif line_stripped.lower().startswith('action:'):
                break
            elif line_stripped.lower().startswith('final answer:'):
                break

            # Continue collecting thought lines (but limit length to avoid capturing analysis)
            elif in_thought and line_stripped:
                thought_lines.append(line_stripped)
                # Cap at 5 lines to keep thoughts concise — avoid capturing full analysis
                if len(thought_lines) >= 5:
                    break

        # Join multi-line thoughts
        thought = ' '.join(thought_lines).strip()

        # Clean up common artifacts
        thought = thought.replace('```', '').strip()

        # Hard cap at 300 chars — thoughts should be brief reasoning, not full content
        if len(thought) > 300:
            thought = thought[:297] + '...'

        return thought if len(thought) > MIN_THOUGHT_LENGTH else ""

    def _extract_plan(self, llm_output: str) -> Optional[List[str]]:
        """Extract execution plan from LLM output"""
        if not llm_output:
            return None

        lines = llm_output.strip().split('\n')
        plan_steps = []
        in_plan = False

        for line in lines:
            line_stripped = line.strip()

            # Start of plan section
            if line_stripped.lower().startswith('plan:') or line_stripped.lower().startswith('**plan:**'):
                in_plan = True
                if '**' in line_stripped:
                    plan_text = line_stripped.split('**PLAN:**', 1)[-1].strip()
                else:
                    plan_text = line_stripped[5:].strip()

                if plan_text and plan_text[0].isdigit():
                    plan_steps.append(plan_text)
                continue

            # End of plan section
            if in_plan and (line_stripped.lower().startswith('thought:') or
                           line_stripped.lower().startswith('action:') or
                           line_stripped.lower().startswith('reflection:')):
                break

            # Collect plan steps
            if in_plan and line_stripped:
                import re
                if re.match(r'^(\d+[\.\):]|\-|\*|Phase\s+\d+)', line_stripped):
                    step = re.sub(r'^(\d+[\.\):]|\-|\*|Phase\s+\d+:?)\s*', '', line_stripped)
                    if step:
                        plan_steps.append(step)

        return plan_steps if len(plan_steps) >= MIN_PLAN_STEPS else None

    def _extract_reflection(self, llm_output: str) -> str:
        """Extract reflection/self-evaluation from LLM output (legacy format)"""
        if not llm_output:
            return ""

        lines = llm_output.strip().split('\n')
        reflection_lines = []
        in_reflection = False

        for line in lines:
            line_stripped = line.strip()

            if line_stripped.lower().startswith('reflection:'):
                in_reflection = True
                reflection_text = line_stripped[11:].strip()
                if reflection_text:
                    reflection_lines.append(reflection_text)
                continue

            if in_reflection and (line_stripped.lower().startswith('thought:') or
                                 line_stripped.lower().startswith('action:') or
                                 line_stripped.lower().startswith('plan:')):
                break

            if in_reflection and line_stripped:
                reflection_lines.append(line_stripped)

        return ' '.join(reflection_lines) if reflection_lines else ""

    def _extract_xml_thinking(self, llm_output: str) -> str:
        """Extract content from <thinking> XML tags using LLMOutputParser"""
        return LLMOutputParser.extract_xml_tag(llm_output, 'thinking') or ""

    def _extract_xml_reflection(self, llm_output: str) -> str:
        """Extract content from <reflection> XML tags using LLMOutputParser"""
        result = LLMOutputParser.extract_xml_tag(llm_output, 'reflection')
        if result:
            reflections = result.split()
            return reflections[-1] if reflections else ""
        return ""

    def _extract_plan_from_thinking(self, thinking_content: str) -> Optional[List[str]]:
        """Extract numbered plan steps from thinking content using LLMOutputParser"""
        return LLMOutputParser.extract_numbered_list(
            thinking_content,
            min_items=MIN_PLAN_STEPS,
            min_item_length=MIN_STEP_LENGTH
        )
